baseURL = 'https://mi-ki-ri.github.io/know-how-to-know/'
languageCode = 'en-us'
title = 'Know How to Know'
theme = 'know-how-to-know'
hasCJKLanguage = true

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true